[env]
TERM = "alacritty"

[font]
size=12

[font.normal]
family="JetBrains Mono NL"

[window]
decorations = "full"
startup_mode = "Maximized"

[window.padding]
x = 20

[cursor.style]
shape = "Underline"
blinking = "On"

[colors.primary]
background = "#111315"
foreground = "#D6DEE8"
dim_foreground = "#95A0AE"
bright_foreground = "#F1F5FB"

[colors.cursor]
text = "#111315"
cursor = "#C9D4E2"

[colors.selection]
text = "#D6DEE8"
background = "#1C222B"

[colors.normal]
black   = "#111315"
red     = "#5B6471"
green   = "#6674A3"
yellow  = "#727B8D"
blue    = "#7C8FE3"
magenta = "#7882BF"
cyan    = "#8BA0D0"
white   = "#C8D1DC"

[colors.bright]
black   = "#2A2F36"
red     = "#6D7787"
green   = "#7B89BC"
yellow  = "#868FA3"
blue    = "#97AAF8"
magenta = "#919CDD"
cyan    = "#A7B9E8"
white   = "#F1F5FB"

[colors.dim]
black   = "#0D0F11"
red     = "#49515C"
green   = "#56628A"
yellow  = "#60697A"
blue    = "#6678C1"
magenta = "#656FA8"
cyan    = "#7487B6"
white   = "#AEB8C4"
